
## Kết quả:

Kết quả huấn luyện mô hình ARIMA cho thấy hệ thống đã xây dựng thành công mô hình dự báo chuỗi thời gian cho biến people_vaccinated_per_hundred trên nhiều quốc gia khác nhau. Sau quá trình Grid Search và lựa chọn tham số tối ưu, mỗi quốc gia được gán một cấu hình ARIMA riêng phù hợp với đặc điểm dữ liệu của mình. Cụ thể, Việt Nam và Trung Quốc được chọn mô hình ARIMA(0,2,1), Hoa Kỳ sử dụng ARIMA(1,2,2), Vương quốc Anh và Brazil sử dụng ARIMA(0,2,2), Ấn Độ sử dụng ARIMA(2,2,3), còn Nam Phi sử dụng ARIMA(0,2,3). Việc phần lớn mô hình có d = 2 cho thấy dữ liệu tiêm vaccine mang tính xu hướng mạnh và cần sai phân bậc cao để đạt trạng thái stationary trước khi huấn luyện. Điều này phù hợp với đặc điểm thực tế của dữ liệu vaccine COVID vì đây là chuỗi tích luỹ có xu hướng tăng liên tục theo thời gian.

Các chỉ số đánh giá như AIC và BIC nhìn chung đều đạt giá trị khá thấp, cho thấy mô hình có khả năng mô tả dữ liệu tương đối tốt mà không quá phức tạp. Đối với Việt Nam và Trung Quốc, giá trị AIC đạt khoảng -6069, thấp hơn đáng kể so với các quốc gia khác, phản ánh chuỗi dữ liệu có tính ổn định rất cao sau khi sai phân. Tuy nhiên, điều này cũng dẫn đến hiện tượng mô hình gần như không còn nhiều biến động để học, thể hiện qua hệ số ma.L1 = 0 và sai số MAE, RMSE bằng 0. Đây là dấu hiệu cho thấy chuỗi sau sai phân gần như phẳng hoàn toàn, khiến mô hình dự báo rất dễ nhưng đồng thời cũng làm giảm giá trị thực tiễn của việc học mô hình. Ngoài ra, các cảnh báo như Covariance matrix is singular or near-singular hay ConvergenceWarning cho thấy quá trình tối ưu hóa Maximum Likelihood gặp khó khăn do dữ liệu quá ổn định hoặc thiếu biến động đáng kể.

Đối với Hoa Kỳ, Vương quốc Anh, Brazil, Ấn Độ và Nam Phi, mô hình tạo ra các giá trị MAE và RMSE khá nhỏ, dao động chủ yếu trong khoảng từ 0.004 đến 0.011, cho thấy dự báo có độ chính xác tương đối cao. Kết quả Walk-Forward Validation cũng cho sai số gần tương đương với tập test, chứng tỏ mô hình có tính ổn định và khả năng tổng quát hóa tốt trên dữ liệu chưa từng được nhìn thấy trước đó. Các hệ số AR (ar.L1, ar.L2) của một số quốc gia như Hoa Kỳ và Ấn Độ có ý nghĩa thống kê khá rõ ràng với p-value rất nhỏ, chứng minh rằng thành phần tự hồi quy có ảnh hưởng đáng kể đến chuỗi dữ liệu. Ngược lại, nhiều hệ số MA có p-value lớn, cho thấy ảnh hưởng của phần Moving Average chưa thực sự mạnh hoặc mô hình đang có hiện tượng dư tham số.

Một điểm đáng chú ý là chỉ số MAPE của tất cả quốc gia đều trả về nan%. Nguyên nhân là do chuỗi dữ liệu sau sai phân có chứa giá trị bằng 0 hoặc rất gần 0, trong khi công thức tính MAPE sử dụng phép chia cho giá trị thực tế nên dẫn đến lỗi không xác định. Đây là hiện tượng thường gặp trong dự báo chuỗi thời gian sau differencing và không ảnh hưởng nghiêm trọng đến toàn bộ mô hình. Trong trường hợp này, MAE và RMSE là hai chỉ số đáng tin cậy hơn để đánh giá hiệu suất mô hình.

## Nhận xét:
Nhìn tổng quát, mô hình ARIMA đã hoạt động tương đối tốt trên dữ liệu tiêm vaccine COVID. Chuỗi dữ liệu sau quá trình resample, differencing và stationarity test đã phù hợp để áp dụng ARIMA. Sai số dự báo nhìn chung thấp, mô hình có khả năng bám sát dữ liệu thực tế và kết quả Walk-Forward Validation cho thấy tính ổn định khá cao. Tuy nhiên, dữ liệu vaccine có tính xu hướng mạnh nhưng mùa vụ yếu nên một số mô hình xuất hiện hiện tượng quá ổn định sau sai phân bậc 2, đặc biệt ở Việt Nam và Trung Quốc. Ngoài ra, các cảnh báo hội tụ và ma trận hiệp phương sai gần suy biến cho thấy mô hình vẫn còn một số hạn chế về mặt thống kê. Dù vậy, xét trên tổng thể, pipeline xây dựng mô hình là hợp lý, đúng quy trình phân tích chuỗi thời gian và đủ khả năng phục vụ cho bài toán dự báo xu hướng tiêm vaccine trong thực tế.
